# Generated by Django 3.2.23 on 2023-11-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_nome_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(related_name='post', to='blog.Category'),
        ),
    ]
