name: CI/CD Workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create Virtual Env
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Run tests
        run: |
          export DJANGO_SETTINGS_MODULE=mysite.settings
          python manage.py test blog/tests
      - name: Run tests with coverage
        run: |
          coverage run manage.py test
      - name: Generate coverage report
        run: |
          coverage report
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: e2e Tests
        run: |
          python manage.py test blog/tests/e2e
